- name: PLAY1
  hosts: local
  connection: local
  tasks:
  - name: Hello from PLAY1 and task-1
    ansible.builtin.debug:
      msg: "Hello from Play-1 and Task1"

- name: PLAY2
  hosts: local
  connection: local
  tasks:
  - name: Hello from PLAY2 and task-2
    ansible.builtin.debug:
      msg: "Hello from Play-1 and Task1"

- name: PLAY3
  hosts: local
  connection: local
  tasks:
  - name: Hello from PLAY3 and task-3
    ansible.builtin.debug:
      msg: "Hello from Play-1 and Task1"
 