- name: variables from promot
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your USERNAME
    private: true

  - name: PASSWORD
    prompt: Please enter your PWD
    private: true
  tasks:
  - name: Printing your information
    ansible.builtin.debug:
      msg: "Hellow Username is: {{ USERNAME }}, Password is {{ PWD }}"    



