- name: understand vars preference
  hosts: local
  connection: local
  vars:
    GREETING: " Hello from PLAY"
  vars_files:
  - course.yaml
  - name: GREETING
    prompt: Please enter the greeting
    private: false
  tasks:
  - name: print the greeting
    vars:
      GREETING: "Hello from TASK"
      ansible.builtin.package:
       msg: "{{ GREETING }}"


