- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 # This is no.
    COURSE: "DevSecops with AWS"  # String
    IS_LIVE: true #boolean
    TOOLS: # List
    - Linux
    - shell
    - ansible
    CONCEPTS: # (Key value pairs, map or dictionary or object
      CI: Jenkins
      SCRIPTING: "Shell,Ansible,terraform,python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration: {{ DURATION }}, is live: {{ IS_LIVE}}, tools are: {{ CONCEPTS }}"

    