- name: function demo
  hosts: local
  connection: local
  tasks:
  - name: convert list in to map
    vars:
      course:
      - { 'key': 'name', 'value': 'asnible'}
      - { 'key': 'duration' , 'value' : '10 Hr'}
      - { 'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: " Course Info : {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "TRINADH KONEY"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: " {{ ip | ansible.utils.ipaddr }}"  
    