- name: shell vs command
  hosts: local
  tasks:
  - name: redirect is output to a file
    # ansible.builtin.command: " uptime"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  - name: redirect is output to a file using command
    ansible.builtin.command: " ls -ltr"
    # ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_output }}" 
