- name: shell vs command
  hosts: local
  tasks:
  - name: redirect is output to a file
    # ansible.builtin.command: " ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"