- name: Variables demo
  hosts: local
  connection: local
  vars:
    COURSE: DevOps
    DURATION: 10Hr
    TRAINER: Sivakumar
  tasks:
  - name: Print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration :{{ DURATION }}, trainer is: {{ TRAINER }}"
      
  - name: print course information again 
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course duration :{{ DURATION }}, trainer is: {{ TRAINER }}"
      